from synchronisers.sync_contacts import sync_contacts
from synchronisers.sync_products import sync_products
from synchronisers.sync_services import sync_services
from synchronisers.sync_purchase_invoices import sync_purchase_invoices
from synchronisers.sync_sales_invoices import sync_sales_invoices

sync_products = sync_products
sync_contacts = sync_contacts
sync_services = sync_services
sync_purchase_invoices = sync_purchase_invoices
sync_sales_invoices = sync_sales_invoices